/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LogoutRouteImport } from './routes/logout'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ConfirmSessionRouteImport } from './routes/confirm-session'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AuthIndexRouteImport } from './routes/_auth/index'
import { Route as AuthUsersIndexRouteImport } from './routes/_auth/users/index'
import { Route as AuthDemoIndexRouteImport } from './routes/_auth/demo/index'
import { Route as AuthDemoConfirmSessionRouteImport } from './routes/_auth/demo/confirm-session'
import { Route as AuthGroupsGroup_idSettingsRouteImport } from './routes/_auth/groups/$group_id/settings'
import { Route as AuthGroupsGroup_idLogsRouteImport } from './routes/_auth/groups/$group_id/logs'
import { Route as AuthGroupsGroup_idHomeRouteImport } from './routes/_auth/groups/$group_id/home'

const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmSessionRoute = ConfirmSessionRouteImport.update({
  id: '/confirm-session',
  path: '/confirm-session',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthUsersIndexRoute = AuthUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthDemoIndexRoute = AuthDemoIndexRouteImport.update({
  id: '/demo/',
  path: '/demo/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthDemoConfirmSessionRoute = AuthDemoConfirmSessionRouteImport.update({
  id: '/demo/confirm-session',
  path: '/demo/confirm-session',
  getParentRoute: () => AuthRoute,
} as any)
const AuthGroupsGroup_idSettingsRoute =
  AuthGroupsGroup_idSettingsRouteImport.update({
    id: '/groups/$group_id/settings',
    path: '/groups/$group_id/settings',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthGroupsGroup_idLogsRoute = AuthGroupsGroup_idLogsRouteImport.update({
  id: '/groups/$group_id/logs',
  path: '/groups/$group_id/logs',
  getParentRoute: () => AuthRoute,
} as any)
const AuthGroupsGroup_idHomeRoute = AuthGroupsGroup_idHomeRouteImport.update({
  id: '/groups/$group_id/home',
  path: '/groups/$group_id/home',
  getParentRoute: () => AuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/confirm-session': typeof ConfirmSessionRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/': typeof AuthIndexRoute
  '/demo/confirm-session': typeof AuthDemoConfirmSessionRoute
  '/demo': typeof AuthDemoIndexRoute
  '/users': typeof AuthUsersIndexRoute
  '/groups/$group_id/home': typeof AuthGroupsGroup_idHomeRoute
  '/groups/$group_id/logs': typeof AuthGroupsGroup_idLogsRoute
  '/groups/$group_id/settings': typeof AuthGroupsGroup_idSettingsRoute
}
export interface FileRoutesByTo {
  '/confirm-session': typeof ConfirmSessionRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/': typeof AuthIndexRoute
  '/demo/confirm-session': typeof AuthDemoConfirmSessionRoute
  '/demo': typeof AuthDemoIndexRoute
  '/users': typeof AuthUsersIndexRoute
  '/groups/$group_id/home': typeof AuthGroupsGroup_idHomeRoute
  '/groups/$group_id/logs': typeof AuthGroupsGroup_idLogsRoute
  '/groups/$group_id/settings': typeof AuthGroupsGroup_idSettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/confirm-session': typeof ConfirmSessionRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/_auth/': typeof AuthIndexRoute
  '/_auth/demo/confirm-session': typeof AuthDemoConfirmSessionRoute
  '/_auth/demo/': typeof AuthDemoIndexRoute
  '/_auth/users/': typeof AuthUsersIndexRoute
  '/_auth/groups/$group_id/home': typeof AuthGroupsGroup_idHomeRoute
  '/_auth/groups/$group_id/logs': typeof AuthGroupsGroup_idLogsRoute
  '/_auth/groups/$group_id/settings': typeof AuthGroupsGroup_idSettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/confirm-session'
    | '/login'
    | '/logout'
    | '/'
    | '/demo/confirm-session'
    | '/demo'
    | '/users'
    | '/groups/$group_id/home'
    | '/groups/$group_id/logs'
    | '/groups/$group_id/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/confirm-session'
    | '/login'
    | '/logout'
    | '/'
    | '/demo/confirm-session'
    | '/demo'
    | '/users'
    | '/groups/$group_id/home'
    | '/groups/$group_id/logs'
    | '/groups/$group_id/settings'
  id:
    | '__root__'
    | '/_auth'
    | '/confirm-session'
    | '/login'
    | '/logout'
    | '/_auth/'
    | '/_auth/demo/confirm-session'
    | '/_auth/demo/'
    | '/_auth/users/'
    | '/_auth/groups/$group_id/home'
    | '/_auth/groups/$group_id/logs'
    | '/_auth/groups/$group_id/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  ConfirmSessionRoute: typeof ConfirmSessionRoute
  LoginRoute: typeof LoginRoute
  LogoutRoute: typeof LogoutRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirm-session': {
      id: '/confirm-session'
      path: '/confirm-session'
      fullPath: '/confirm-session'
      preLoaderRoute: typeof ConfirmSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/': {
      id: '/_auth/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/users/': {
      id: '/_auth/users/'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthUsersIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/demo/': {
      id: '/_auth/demo/'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof AuthDemoIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/demo/confirm-session': {
      id: '/_auth/demo/confirm-session'
      path: '/demo/confirm-session'
      fullPath: '/demo/confirm-session'
      preLoaderRoute: typeof AuthDemoConfirmSessionRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/groups/$group_id/settings': {
      id: '/_auth/groups/$group_id/settings'
      path: '/groups/$group_id/settings'
      fullPath: '/groups/$group_id/settings'
      preLoaderRoute: typeof AuthGroupsGroup_idSettingsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/groups/$group_id/logs': {
      id: '/_auth/groups/$group_id/logs'
      path: '/groups/$group_id/logs'
      fullPath: '/groups/$group_id/logs'
      preLoaderRoute: typeof AuthGroupsGroup_idLogsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/groups/$group_id/home': {
      id: '/_auth/groups/$group_id/home'
      path: '/groups/$group_id/home'
      fullPath: '/groups/$group_id/home'
      preLoaderRoute: typeof AuthGroupsGroup_idHomeRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthIndexRoute: typeof AuthIndexRoute
  AuthDemoConfirmSessionRoute: typeof AuthDemoConfirmSessionRoute
  AuthDemoIndexRoute: typeof AuthDemoIndexRoute
  AuthUsersIndexRoute: typeof AuthUsersIndexRoute
  AuthGroupsGroup_idHomeRoute: typeof AuthGroupsGroup_idHomeRoute
  AuthGroupsGroup_idLogsRoute: typeof AuthGroupsGroup_idLogsRoute
  AuthGroupsGroup_idSettingsRoute: typeof AuthGroupsGroup_idSettingsRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthIndexRoute: AuthIndexRoute,
  AuthDemoConfirmSessionRoute: AuthDemoConfirmSessionRoute,
  AuthDemoIndexRoute: AuthDemoIndexRoute,
  AuthUsersIndexRoute: AuthUsersIndexRoute,
  AuthGroupsGroup_idHomeRoute: AuthGroupsGroup_idHomeRoute,
  AuthGroupsGroup_idLogsRoute: AuthGroupsGroup_idLogsRoute,
  AuthGroupsGroup_idSettingsRoute: AuthGroupsGroup_idSettingsRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  ConfirmSessionRoute: ConfirmSessionRoute,
  LoginRoute: LoginRoute,
  LogoutRoute: LogoutRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
